name: Setup, Build, and Publish
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # the code
        uses: actions/checkout@v6

      - name: Install # missing packages
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes musl-tools

      - name: Cache # the build
        uses: Swatinem/rust-cache@v2
        with:
          key: aarch64-unknown-linux-musl
          shared-key: sve-backend

      - name: Build # the binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: aarch64-unknown-linux-musl
          args: "--release --locked"

      - name: Package binary
        run: |
          cd target/aarch64-unknown-linux-musl/release
          mv sve_backend bootstrap
          zip lambda.zip bootstrap
          mv lambda.zip ../../../

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: lambda
          path: lambda.zip

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      SQLX_OFFLINE: true
      CROSS_CONTAINER_OPTS: --network=host
    steps:
      - uses: actions/checkout@v6
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: aarch64-unknown-linux-musl
          shared-key: sve-backend
      - uses: houseabsolute/actions-rust-cross@v1
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          SQLX_OFFLINE: "true"
        with:
          command: "test"
          target: aarch64-unknown-linux-musl
          args: "--release --locked"

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: lambda
      - uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: sve-backend
          zip_file: lambda.zip